version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=tasking
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql/data

